# Generated by Django 5.1 on 2024-08-21 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('autores', models.CharField(max_length=255)),
                ('resumo', models.CharField(max_length=255)),
                ('abstract', models.TextField()),
                ('palavras_chave', models.TextField()),
                ('data', models.DateField(blank=True, null=True)),
                ('revista', models.CharField(max_length=255)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='arquivos/')),
            ],
        ),
    ]
