# Generated by Django 5.1 on 2024-09-30 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artigo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigo',
            name='ultima_modificacao',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
