# Generated by Django 5.1 on 2024-11-04 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artigo', '0004_artigo_autor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artigo',
            options={'permissions': [('pode_publicar', 'Pode publicar artigos'), ('pode_visualizar', 'Pode visualizar artigos')]},
        ),
        migrations.AddField(
            model_name='artigo',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
    ]
