# Generated by Django 5.1 on 2024-11-23 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artigo', '0005_alter_artigo_options_artigo_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artigo',
            options={},
        ),
    ]
